//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect2Fit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Connect2FitEntities : DbContext
    {
        public Connect2FitEntities()
            : base("name=Connect2FitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<ScheduleItems> ScheduleItems { get; set; }
    
        public virtual ObjectResult<string> GetRoles(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GetRoles", userIDParameter);
        }
    
        public virtual ObjectResult<GetDBUsersModel_Result> GetDBUsersModel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDBUsersModel_Result>("GetDBUsersModel");
        }
    
        public virtual ObjectResult<GetDBClassesModel_Result> GetDBClassesModel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetDBClassesModel_Result>("GetDBClassesModel");
        }
    }
}
