//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Connect2Fit
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScheduleItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScheduleItems()
        {
            this.AspNetUsers1 = new HashSet<AspNetUsers>();
        }
    
        public int id { get; set; }
        public System.DateTime ClassDateTime { get; set; }
        public string instructor_Id { get; set; }
        public string ClassName { get; set; }
        public int maxAttendies { get; set; }
        public string sessionTime { get; set; }
        public bool sessionEnded { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers1 { get; set; }
    }
}
